rm `is_tlm`  as input arguments to all CausalLM classes (#396) (#408)
https://github.com/quic/efficient-transformers/pull/306

After above PR was posted, we found that `QEFFTransformersBase` class
continued to have the now deprecated `is_tlm` as input argument.

This is causing some vLLM unit tests to fail because `is_tlm` was being
passed to `QEFFTransformersBase.__init__` even though the `__init__` did
not accept `is_tlm` as argument:

` INFO 05-08 03:07:01 qaic.py:258] Unable to access HF hub due to an
exception: LlamaForCausalLM.__init__() got an unexpected keyword
argument 'is_tlm'`

---------

Signed-off-by: eplatero <quic_eplatero@quicinc.com>